### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SoibamArunaChanu**

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
@SoibamArunaChanu please fix.

**Comment by lukasc-ubc** [comment]
@SoibamArunaChanu do you plan to fix, or can I close this PR?

**Comment by SoibamArunaChanu** [comment]
Sorry for the late reply. Caught into some unavoidable personal problems. I will fix the problem as soon as possible. Kindly do not close it yet.

**Comment by SoibamArunaChanu** [comment]
verification error

Hello Lucas,
Attached is how I got it while I ran the SiEPIC Verification for my design. I am trying to figure out which is the "Shapes outside component" error, which was earlier mentioned to be fixed. I cannot find it out. Can you please help me out with this? Thanks.

**Comment by SoibamArunaChanu** [comment]
Hello,
I have added the DevRec and PinRec to my custom design. Now, The flattened component error is coming. How can I solve this?

Also, The disconnected pin is still showing. Please, give me some suggestions to fix these. Thank you.
flattened error

**Comment by lukasc-ubc** [comment]
This is the file arunaPBS3:
image

The problem is that the geometries are not inside a Cell, and do not have their own Pins and DevRecs
image

For PBS1, there are also errors:
image
these are coming because the geometries for your component are not inside it's own Cell.
image

to put them into a cell, use Selection > Make Cell:
image

**Comment by SoibamArunaChanu** [comment]
@lukasc-ubc It is showing "No layout errors detected" to my klayout. I don't understand why my checks are still not successful here. Kindly help.
no error

**Comment by lukasc-ubc** [comment]
Did you see the comment above? It looks like you are running a really old version of the tools and PDK, hence you don't have all the rules on your side. You can also download the error file and load it to see the errors.

**Comment by lukasc-ubc** [comment]
@SoibamArunaChanu

**Comment by SoibamArunaChanu** [comment]
@lukasc-ubc If I'm getting it right, it looks like the errors are coming from the files "arunaPBS3, arunaPBS4, arunaPBS5, and arunaPBS6". 
error_

Earlier, I uploaded a total of 6 files. But, I have fixed errors for only two files (arunaPBS1 and arunaPBS2), and submitted only these two files. However, it still looks like the rest of the earlier submitted files (not fixed errors) are still going for verification.

Am I getting it right? If so, to upload only these two files for verification (arunaPBS1 and arunaPBS2), how should I do this?

And if the issue is because of my old version tools, I will change and fix it. I would like to know how much time I still have to submit.

Thank you.

**Comment by SoibamArunaChanu** [comment]
Now, I see all my previously uploaded 6 files are still there in the submission folder.
to delete

I am trying to delete some of the files, but the delete option is not active. Why is it so?

**Comment by lukasc-ubc** [comment]
you have to click on the individual file.  Then delete them.

image

**Comment by lukasc-ubc** [comment]
it looks like I had write access to your fork, and so deleted them for you.

**Comment by lukasc-ubc** [comment]
Do you have the PCell that created these designs?  Would you be able to contribute it to the SiEPIC EBeam_Beta library?  (via pull request).

thanks
Lukas

**Comment by lukasc-ubc** [comment]
It would be great if you could finish today, but early tomorrow would be ok as well.

**Pull request merged**
