### PR TITLE
new pull request for OAS file

### PR DESCRIPTION
**Pull request by DingChunfjw**
The previous GDS file was too large, so I creat new pull request and re-uploaded it in OAS format

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Tons of errors:

Error: Shapes outside component: Shapes for device layers need to be inside a component. At minimum, they must be inside a cell and inside a DevRec shape. Read more about requirements for components: https://github.com/SiEPIC/SiEPIC-Tools/wiki/Component-and-PCell-Layout

**Comment by DingChunfjw** [comment]
I received an email earlier, indicating that the GDS file(EBeam_HFUT_May_Fjw_04.GDS) I submitted before was too large and there might be an error, so I resubmitted the OAS version with a smaller size.

Some errors that had not occurred before but occurred under the OAS version. So I took some time to fix these errors.

**Comment by lukasc-ubc** [comment]
Thank you!

**Comment by lukasc-ubc** [comment]
@DingChunfjw 
Unfortunately, the grating coupler cell you are using is not correct.  We replace all the grating couplers with ones that we know work correctly.   Please use "GC_TE_1550_1550_8degOxide_BB" from the latest PDK:
image

Otherwise, this is what your design will look like, and won't be measurable.
image

thank you

**Pull request merged**
