### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by omidesml**

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Tons of errors in the automated checker.

**Comment by omidesml** [comment]
@lukasc-ubc not sure why. I get errors of (1) disconnected pins and (2) labels despite having all the labels generated uniquely. 
Disconnected pins seem to be fictitious

**Comment by lukasc-ubc** [comment]
Hi @omidesml 

The origin of your cell is not in the correct position.  You can check the merging locally, by running

```
cd merge
python EBeam_merge.py
```

image

**Comment by omidesml** [comment]
@lukasc-ubc 
I edited the origin and looks fine in merging locally 
image

**Pull request merged**
