### PR TITLE
Marked TM wrong. Fixed. Needs manual approval (spiral)

### PR DESCRIPTION
**Pull request by silkBee**
Needs manual approval due to the spiral

### CODE REVIEW

**Comment by silkBee** [comment]
Could you please manually approve this?   This is hopefully the last version of the spiral one.  
This time I had to change TE mode to TM mode in the label for one MZI. Thanks!

**Comment by silkBee** [comment]
I made a change to the spiral one after pr/162.  I realized one MZI was TM mode but the label said TE, and I fixed it and resubmitted pr 168

**Comment by lukasc-ubc** [comment]
I don't see any spirals.  just ring resonators.  Is this correct?

image

**Comment by silkBee** [comment]
I submitted PR168 EBeam_Lily_Yuan_A (spiral), then while waiting for manual approval, I also tried to submit EBeam_Lily_Yuan_B (resonators) but could see the "create a new pull request" button.    Shall I redo either one, or both?

**Comment by silkBee** [comment]
Looks like I should not have upload B while waiting for A.  
I just submitted PR180 EBeam_Lily_Yuan_A (spiral). Please help manually approve and merge.  Thanks Prof Lucas.

**Pull request merged**
