### PR TITLE
1st upload

### PR DESCRIPTION
**Pull request by smich86**

### CODE REVIEW

**Comment by smich86** [comment]
Hi, from my own verification, i dont see any layout error.
Screenshot 2024-05-08 at 10 32 00 PM

**Comment by lukasc-ubc** [comment]
Your layout is getting cropped

**Comment by lukasc-ubc** [comment]
I found it.  We added a new rule:
The grating coupler spacing (pitch) must be at least 60.0 microns.

There are only two places with this problem.  If you move the top right circuits up by 20 µm that should fix it.

image


image
image

**Comment by lukasc-ubc** [comment]
@omidesml could you make an announcement about this new rule in the discussion forum?

**Comment by smich86** [comment]
Hi, i have amended the layout gds according. However, i am getting the error of "PullRequest / comment-in-pr (pull_request_target)"

**Comment by lukasc-ubc** [comment]
I just checked your files, and they still have the < 60 µm problem.
Don't worry about the comment-in-pr problem...
image

**Comment by smich86** [comment]
Hi Lucas,

I have moved all grating couplers, at least 60um (from the ruler measurement) from adjacent GCs. Are you able to verify for me if all have been done successfully?

Once again, i did my verification check without error

**Comment by omidesml** [comment]
There is still 40um spacing between adjacent grating couplers in the latest files

**Comment by lukasc-ubc** [comment]
the layout indeed looks error free.   Let me investigate why there is an error in the automated check.

You are planning on purchasing 8 SEM images?

image

**Comment by lukasc-ubc** [comment]
are you sure you uploaded the correct file?  here is what I see:

image

**Comment by smich86** [comment]
Hi, i have tried many times with no success to get the layout verified. I have checked through all possible areas for faults. Please assist in finding the root cause. The latest file looks like the attached image. Thanks.
Screenshot 2024-05-12 at 3 57 13 PM

**Comment by lukasc-ubc** [comment]
You are very close!

You have uploaded two files -- the .gds file is correct, and the .oas file still has the < 60 µm error.  So it is quite easy - just remove the .oas file, and only submit one file -- the .gds one.

thank you

**Comment by smich86** [comment]
I have uploaded my file before the stipulated deadline. However, i was experiencing much problem due to DRC failures. As such, i did not click on the 2 questions to claim my 2 points. I realized that the boxes are frozen right now. So am i eligible for the points for submission before the deadline?

https://learning.edx.org/course/course-v1:UBCx+Phot1x+1T2024a/block-v1:UBCx+Phot1x+1T2024a+type@sequential+block@f5daafa62da9496e9ed1ac4f6777b562/block-v1:UBCx+Phot1x+1T2024a+type@vertical+block@7826efe9fb43467c91be122e9829f057

**Pull request merged**
