### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by boy4429856821**
ColemanTheSoulMan's Edx course design submission

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Error: Cell bounding box / extent (610.96, 425.41) is larger than the maximum size of 605.0 X 410.0 microns

**Comment by boy4429856821** [comment]
I believe I fixed bounding box issue, verifying now

**Comment by boy4429856821** [comment]
nvm I was not changing the right parameters..., was not editing in center/size tab... reuploading now

**Comment by boy4429856821** [comment]
with resizing, didn't notice some designs were outside the cell bounding box (had to fix that as well...)

**Pull request merged**
