### PR TITLE
Final updated files

### PR DESCRIPTION
**Pull request by SoibamArunaChanu**

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
@SoibamArunaChanu 

Unfortunately, several of your designs have a big problem (which has an easy fix).  Namely, you have changed the cell names of the grating couplers.  As described in the Readme file, the cell names with _BB cannot be changed, otherwise the replacement script does not recognize them.  You changed their names to PhCxxxx.

So as is, your design won't function.  Can you please fix asap?

The designs that have this problem are:
PBS1
PBS3
PBS5

image

**Comment by SoibamArunaChanu** [comment]
@lukasc-ubc Thank you for pointing out the problem. 
I am not quite sure how I can fix this since it is not shown here.
gc_error

I have deleted the grating couplers and added them again. Will this fix the problem?

**Comment by lukasc-ubc** [comment]
let me check.

**Comment by lukasc-ubc** [comment]
I'm not sure where the PhC14$1 is coming from.  But indeed, the file you uploaded doesn't seem to have it!  Strange...  I am investigating and will try to fix it.

**Comment by lukasc-ubc** [comment]
strange bug in KLayout?  https://github.com/KLayout/klayout/issues/1714

**Comment by SoibamArunaChanu** [comment]
I found out that, I have used the name "PhCXX" to save my .gds files exported from Lumerical FDTD. 

I am not sure why some of the layouts are having this problem, and some are not. I am freshly designing the ones with the problem.

**Pull request merged**
