### PR TITLE
a GDS file designed by HFUT fjw 

### PR DESCRIPTION
**Pull request by DingChunfjw**

### CODE REVIEW

**Comment by omidesml** [comment]
You have layout errors. Please check Functional Verification in KLayout before uploading. 
Most importantly: (1)you have waveguide connection misalignment and (2) grating couplers position is wrong -- they should be left-to-right 
Please fix and reupload

**Comment by lukasc-ubc** [comment]
Now there are zero files changed in this PR!

**Comment by DingChunfjw** [comment]
designs by fjw

**Comment by DingChunfjw** [comment]
Due to the presence of irregular components in my design, there are no pins on this particular component. As a result, the waveguide's pins appear to be unconnected. However, the design has been inspected and contains no errors, which is why errors have been reported previously in this area. I have made modifications to the pins, enabling them to be automatically detected and preventing any errors from occurring.

**Comment by lukasc-ubc** [comment]
I notice that in your design that you have oversampled the shape, namely too many points. See screenshot.  It leads to unnecessarily large files, plus may cause some errors in the fabrication.  
image

Also I suggest saving your file in OASIS format, which is much smaller.

Regarding Pins and DevRec layers, please add them in using the following description: https://github.com/SiEPIC/SiEPIC-Tools/wiki/Component-and-PCell-Layout

thank you
Lukas

**Comment by DingChunfjw** [comment]
> I notice that in your design that you have oversampled the shape, namely too many points. See screenshot. It leads to unnecessarily large files, plus may cause some errors in the fabrication. image
> 
> Also I suggest saving your file in OASIS format, which is much smaller.
> 
> Regarding Pins and DevRec layers, please add them in using the following description: https://github.com/SiEPIC/SiEPIC-Tools/wiki/Component-and-PCell-Layout
> 
> thank you Lukas

Dear Lukas：


Due to the complexity of spiral grating code, the function of automatically adding pin is not used for the time being, so the connection of waveguide relies on manual operation. But I can ensure that the design was carefully thought out, and the placement and wiring were also considered.


I have converted the file format to OAS format. Should I fork and submit it on github again?


If there are any other problems, please let me know and I will correct it.


Thank you 

FJW

**Pull request merged**
