### PR TITLE
Merge my files

### PR DESCRIPTION
**Pull request by raghi1991**
Hi I am Raghi El Shamy a PhD student from McMaster University. I have had the permission of Prof. Lucas to add my designs in this run. I have uploaded my layout file "EBeam_raghi1991_D1" and it passed the verification step. Could you please merge it. Thanks

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
@raghi1991 

there are some errors:

Files for verification; EBeam_raghi1991_B.oas
EBeam_raghi1991.oas
EBeam_raghi1991_B.oas
EBeam_raghi1991_C.oas
EBeam_raghi1991_D1.oas
EBeam_raghi1991_E.oas
Running verification on EBeam_raghi1991_B.oas
1 errors detected for EBeam_raghi1991_B.oas
KLayout SiEPIC-Tools version 0.5.7
SiEPIC-EBeam-PDK Python module: siepic_ebeam_pdk, KLayout technology: EBeam
SiEPIC-EBeam-PDK Python module: pymacros
No libraries associated to EBeam technology
SiEPIC_EBeam_Library_Beta, version 0.4.8
Error: layout does not have 1 top cell. It has 17.
Unknown error occurred
1
Done verification on EBeam_raghi1991_B.oas
Running verification on EBeam_raghi1991.oas
1 errors detected for EBeam_raghi1991.oas
KLayout SiEPIC-Tools version 0.5.7
SiEPIC-EBeam-PDK Python module: siepic_ebeam_pdk, KLayout technology: EBeam
SiEPIC-EBeam-PDK Python module: pymacros
No libraries associated to EBeam technology
SiEPIC_EBeam_Library_Beta, version 0.4.8
Error: layout does not have 1 top cell. It has 16.
Unknown error occurred
1
Done verification on EBeam_raghi1991.oas
Running verification on EBeam_raghi1991_B.oas
1 errors detected for EBeam_raghi1991_B.oas
KLayout SiEPIC-Tools version 0.5.7
SiEPIC-EBeam-PDK Python module: siepic_ebeam_pdk, KLayout technology: EBeam
SiEPIC-EBeam-PDK Python module: pymacros
No libraries associated to EBeam technology
SiEPIC_EBeam_Library_Beta, version 0.4.8
Error: layout does not have 1 top cell. It has 17.
Unknown error occurred
1
Done verification on EBeam_raghi1991_B.oas
Running verification on EBeam_raghi1991_C.oas
1 errors detected for EBeam_raghi1991_C.oas
KLayout SiEPIC-Tools version 0.5.7
SiEPIC-EBeam-PDK Python module: siepic_ebeam_pdk, KLayout technology: EBeam
SiEPIC-EBeam-PDK Python module: pymacros
No libraries associated to EBeam technology
SiEPIC_EBeam_Library_Beta, version 0.4.8
Error: layout does not have 1 top cell. It has 2.
Unknown error occurred
1

**Comment by raghi1991** [comment]
Hi Prof. Lucas
It is only the EBeam_raghi1991_D1 file that I need to merge. I did the check to this one and it is clear. Please discard the previous ones as they had errors.

**Comment by lukasc-ubc** [comment]
Please remove the files you do not need.  Update your pull request so that only the file you want is there..
Also, please use the filename “openEBL_xxx” instead of “EBeam_xxx”.

Thank you

**Comment by raghi1991** [comment]
Ok I will do that. Many thanks

**Comment by raghi1991** [comment]
Hi Prof. Lucas,
I have deleted my old files and uploaded the new/final ones that I want to merge. The final files are: openEBL_raghi1991_D1.oas and openEBL_raghi1991_E1.oas. They have passed rule checks. Could you please merge. Thanks

**Comment by raghi1991** [comment]
Hi Prof. Lucas,
I have included some SEMs in my layouts that I am willing to pay for if that is possible. I saw your comment about SEMs and that they are stripped off for openEBL filenames. So should I rename my files to EBeam before you merge them? Thanks

**Pull request closed without merging**
