### PR TITLE
Please Merge Ebeam_C_Adikarige.gds

### PR DESCRIPTION
**Pull request by chamithri-A**

### CODE REVIEW

**Comment by omidesml** [comment]
your second design 'openEBL_CAdikarige.gds' does not have opt_in labels. Please add unique labels and change the name to EBeam please. Thanks! Also, if you could de-embed  the MZIs in the cascaded filter it'd be useful later analyzing the data.

**Comment by chamithri-A** [comment]
Hi, I don't want to use the older design, i changed them in the new one which does have the opt-in labels. I'm not sure what is a cascaded filter? are you talking about making imbalnce bigger and spiral like?

**Comment by lukasc-ubc** [comment]
Error checker says:

Error: opt_in label: missing: Automated test opt_in labels are required for measurements on the Text layer.

**Review by chamithri-A — COMMENTED** [review]
final layout

**Comment by lukasc-ubc** [comment]
read the error messages:
https://github.com/SiEPIC/openEBL-2024-05/actions/runs/9140955668/job/25134881026?pr=152

**Comment by chamithri-A** [comment]
> read the error messages: https://github.com/SiEPIC/openEBL-2024-05/actions/runs/9140955668/job/25134881026?pr=152

Hi, I'm pretty new to github, i think it keeps asking about the older file which had no opt in labels. I only want to submit the new one with the fixes called "C_Adikarige_final". Its uploaded in my own repository but i dont see it in submissions in the main. I also cant seem to delete the old one.

**Pull request closed without merging**
