### PR TITLE
TM devices bend radii were too small 

### PR DESCRIPTION
**Pull request by boy4429856821**
TM devices bend radii were too small (5 microns).  Adjusted Bend radii to 15 microns based on PDK recommendation as well as the fact that the devices needed this change due to the confinement properties of TM vs TE.

### CODE REVIEW

**Comment by boy4429856821** [comment]
no_layout_error


I do not see a layout issue... do you see an issue?

**Comment by lukasc-ubc** [comment]
Looks like there are two errors. Can you download the error file from the automated checker?

**Comment by boy4429856821** [comment]
[ErrorFile.txt](https://github.com/SiEPIC/openEBL-2024-05/files/15210507/ErrorFile.txt)

Is this the error file you are talking about?

**Comment by boy4429856821** [comment]
[ErrorFile.txt](https://github.com/SiEPIC/openEBL-2024-05/files/15210515/ErrorFile.txt)

whoops here's the entire cell

**Comment by boy4429856821** [comment]
Alright the tool was not telling me that my path length is tool small for the bend radius I was using...

**Comment by boy4429856821** [comment]
Alright I had to remove one device... will have to investigate another day... Think this is enough pull requests for one day :)

**Comment by boy4429856821** [comment]
Alright got the device back into the layout area. Switched the MIs to the use the Directional couplers which are smaller in size.

**Pull request merged**
