### PR TITLE
This is my final design for submission

### PR DESCRIPTION
**Pull request by aryasubh**

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Can you please fix these errors?

```
Files for verification; OpenEBL_SubhashArya.gds
openEBL_SubhashArya_OFG.gds
Running verification on OpenEBL_SubhashArya.gds
1 errors detected for OpenEBL_SubhashArya.gds
KLayout SiEPIC-Tools version 0.5.8
SiEPIC-EBeam-PDK Python module: siepic_ebeam_pdk, KLayout technology: EBeam
SiEPIC-EBeam-PDK Python module: pymacros
No libraries associated to EBeam technology
SiEPIC_EBeam_Library_Beta, version 0.4.8
Error: layout does not have 1 top cell. It has 2.

Running verification on openEBL_SubhashArya_OFG.gds
1 errors detected for openEBL_SubhashArya_OFG.gds
KLayout SiEPIC-Tools version 0.5.8
SiEPIC-EBeam-PDK Python module: siepic_ebeam_pdk, KLayout technology: EBeam
SiEPIC-EBeam-PDK Python module: pymacros
No libraries associated to EBeam technology
SiEPIC_EBeam_Library_Beta, version 0.4.8
Error: layout does not have 1 top cell. It has 2.
```

here is how to fix this:
image

**Comment by aryasubh** [comment]
Yes, I can fix errors. How should I re-submit the error-free layout?

**Comment by lukasc-ubc** [comment]
```
Error: Grating coupler: minimum spacing: The grating coupler spacing (pitch) must be at least 60.0 microns.
Error: Grating coupler: minimum spacing: The grating coupler spacing (pitch) must be at least 60.0 microns.
Error: Grating coupler: minimum spacing: The grating coupler spacing (pitch) must be at least 60.0 microns.
Error: Grating coupler: minimum spacing: The grating coupler spacing (pitch) must be at least 60.0 microns.

```

**Comment by aryasubh** [comment]
Thank you for merging my file.

**Pull request merged**
