### PR TITLE
Create EBeam_GANEWBURGH.gds

### PR DESCRIPTION
**Pull request by ganewburgh**
UPDATED GDS FILE

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
It seems there is something wrong with your file.  I can't open it.

image

**Comment by ganewburgh** [comment]
I will send via google mail as well ***@***.***). I noticed that when I save the Klayout file and re-open laser and detectors are lost.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by lukasc-ubc** [comment]
You don't need the laser and detector.

**Comment by lukasc-ubc** [comment]
Hello.. your file has a file size of only 1 Byte.

Can you please re-upload the full file?

I haven't seen anyone do this before.  How are you uploading your file?  Using GitHub Desktop, or the GitHub web interface?  Is there something on your computer like a firewall that prevents the file from being uploaded?

thank you

image

**Comment by ganewburgh** [comment]
would you use the file i sent you and save it to github? i can try again, but the process is clunky at best

**Comment by lukasc-ubc** [comment]
image

@ganewburgh your design (PR/99) has multiple top cells. Please delete the extra ones.  

thank you

**Pull request closed without merging**
