### PR TITLE
Final corrected submission

### PR DESCRIPTION
**Pull request by ogzz23**
I finished verification, there are still some errors but they are related to inverse design structure, which are imported as gds file externally.

### CODE REVIEW

**Comment by ogzz23** [comment]
I finished verification, there are still some errors but they are related to inverse design structure, which are imported as gds file externally.

**Comment by ogzz23** [comment]
I converted the name as requested like from E_beam_openEBL_mehmetunlu_S tp openEBL_mehmetunlu_S

**Comment by lukasc-ubc** [comment]
For your inverse designed structures, please be sure to create a Cell add the DevRec and PinRec layers to your custom cells: https://github.com/SiEPIC/SiEPIC-Tools/wiki/Component-and-PCell-Layout

**Comment by lukasc-ubc** [comment]
@ogzz23

**Comment by lukasc-ubc** [comment]
@ogzz23 wonderful you got it to 0 errors!  Thank you.

Do you have the PCells for your design that you could contribute?  You could add them to the EBeam_Beta library in the PDK, using a Pull Request.

thank you!
Lukas

**Comment by ogzz23** [comment]
Dear Prof. Chrostowski,

I saw that you added SEM images of my inverse design structures on the OpenEBL web page, and I was very happy, thank you! I will also add it to the EBeam_Beta library section as soon as possible.

I was also going to ask you a question regarding this subject. These structures we inversely designed work in the range of 1.54-1.60 µm, but measurements are generally performed up to 1.58 µm in this openEBL program. Is there a chance to measure up to 1.60 µm, or would you like to contribute to this inverse design study in the measurement section? I want to ask :)

Thanks!

Ahmet

**Pull request merged**
