### PR TITLE
dmascare design 2024_05_07

### PR DESCRIPTION
**Pull request by dmascare**
Dmascare design layout submission
dmascare design 2024_05_07

### CODE REVIEW

**Comment by dmascare** [comment]
This is dmascare's pull request for the design review

**Comment by lukasc-ubc** [comment]
Automated test opt_in labels are required for measurements on the Text layer. 

Details on the format for the opt_in labels can be found at https://github.com/lukasc-ubc/SiEPIC-Tools/wiki/SiEPIC-Tools-Menu-descriptions#connectivity-layout-check

**Comment by dmascare** [comment]
I am not sure why this fails.  When I run the functional verification in klayout it says "no layout errors detected."
Please advise

**Comment by dmascare** [comment]
I did this before I submitted and it said there were no errors.

**Comment by lukasc-ubc** [comment]
sorry, this was my fault. I was editing the automated verification.

**Pull request merged**
